### ISSUE TITLE
gitlab_branch_protection - Doesn't work if default branch protection matches the desired protection level

### ISSUE THREAD

**Issue by kemra102** [gitlabhq/terraform-provider-gitlab#671] opened 2021-07-21 12:46 UTC
### Terraform Version
```sh
$ terraform version
Terraform v1.0.1
on linux_amd64
```

### Affected Resource(s)
- `gitlab_branch_protection`

### Terraform Configuration Files
```hcl
resource "gitlab_project" "project" {
  name               = var.name
  path                 = var.path
  description       = var.description
  namespace_id = var.group_id
  default_branch = "main"
  ...
}

resource "gitlab_branch_protection" "main" {
  branch                                        = "main"
  merge_access_level                  = "maintainer"
  project                                        = gitlab_project.project.id
  push_access_level                     = "no one"
  code_owner_approval_required = true
}
```

### Expected Behavior
With the project default set such that the default branch protection is enabled we should be able to create the repo and set the additional options present in the `gitlab_branch_protection` resource such as `code_owner_approval_required`.

### Actual Behavior
An error stating that the branch protection already exists:
```sh
Error: protected branch "main" on project "1234" already exists: {ID: 1234 Name:main PushAccesslevels;[0x0002828a0] MergeAccessLevels:[0xc0002828d0] UnprotectedAccessLevels[] AllowForcePush:false CodeOwnerApprovalRequired:false}
```
For now we are working around this by importing the `gitlab_branch_protection` then running a `terraofrm` apply again which re-creates (deletes/creates) the resource correctly.

### Important Factoids
The issue (this is an educated guess at best) seems to come down to one important fact, if the project default "default branch" is set to protected and that is in fact the setting we want then we are locked out of configuring other settings on that branch. Setting the project default to NOT have a protected default branch is NOT an option for us as we are subject to very strict security requirements.

### References
- GH-667

**Comment by mgriffin13** [comment] 2021-07-23 13:30
I am experiencing the same behavior. We are using Terraform Enterprise, so importing the resource becomes much more challenging for us.

Would it be possible for TF to just delete/create the gitlab_branch_protection resource initially if it detects it already exists?

**Comment by mgriffin13** [comment] 2021-07-23 13:44
After some more testing, I think that setting the **Default branch protection** to `Not protected` might be a suitable workaround. If TF is creating the Gitlab project and immediately also creating the `gitlab_branch_protection` resource, then it's functionally equivalent to using the `Fully protected` setting. Not ideal, because it means if someone creates a Gitlab project outside of TF then you lose the branch protection, but in my case, we've locked down the Gitlab group so that only TF can create projects, so I think that workaround will suffice until this issue is resolved.

**Comment by drpebcak** [comment] 2021-07-26 22:07
I've also seen this issue, although for me it's started happening even when the protection level doesn't match - I want to set push to 'maintainers' and merge to 'developers'. That has started failing recently:

```
 Error: protected branch "main" on project "<project>" already exists: {ID:41045354 Name:main PushAccessLevels:[0xc00034e930] MergeAccessLevels:[0xc00034e960] UnprotectAccessLevels:[] AllowForcePush:false CodeOwnerApprovalRequired:false}
```

**Comment by Stromweld** [comment] 2021-08-03 20:29
This started failing for us as well since 3.7 release

**Comment by Stromweld** [comment] 2021-08-03 21:36
there must be a bug in the code here as this is the only commit recently touching branch protection https://github.com/gitlabhq/terraform-provider-gitlab/commit/89de4bd5e56d7495984784b6da79a78c93bce910

**Comment by armsnyder** [comment] 2021-08-03 22:00
@Stromweld

> there must be a bug in the code here as this is the only commit recently touching branch protection

I think actually the behavior was introduced in #583, though it's not fully clear to me yet whether it's a bug.

Is there a corresponding behavior in GitLab where you can create a new project with a default branch without the default branch being automatically protected?

From what I can tell, GitLab does not let you set a default branch on an empty project, and if you ask it to initialize a project with a README, it sets the default branch as protected for you.

@mgriffin13 

> Would it be possible for TF to just delete/create the gitlab_branch_protection resource initially if it detects it already exists?

Generally no, Terraform does not allow you to auto-import things. We would need some kind of workaround.

@kemra102

Can you or somebody clarify the intention behind creating a `gitlab_project` with a `default_branch` set but without settings `initialize_with_readme=true`? I don't think that's valid because you can't set a default branch on an empty repository. Some more details about your use case would help!

**Comment by Stromweld** [comment] 2021-08-03 22:19
we do have the initialize with readme set. I'm not sure I understand your question.
> Is there a corresponding behavior in GitLab where you can create a new project with a default branch without the default branch being automatically protected?
I'm not sure I understand your question.
before 3.7 project would be created and initialized with a readme. then branch_protection resource would adjust the main branches protection settings according to our settings in code. no-one push, dev+maintainers can merge, no force push, etc...

**Comment by kemra102** [comment] 2021-08-04 09:34
> @kemra102
> 
> Can you or somebody clarify the intention behind creating a `gitlab_project` with a `default_branch` set but without setting `initialize_with_readme=true`? I don't think that's valid because you can't set a default branch on an empty repository. Some more details about your use case would help!

Apologies, the code for the `gitlab_project` resource code was snipped, we DO set `initialize_with_readme` to `true`. That full resource would be:

```hcl
resource "gitlab_project" "project" {
  name                                                       = var.name
  path                                                         = var.name
  description                                              = var.description
  namespace_id                                        = var.group_id
  default_branch                                        = "main"
  merge_method                                        = "ff"
  approvals_before_merge                         = var.approvals_before_merge
  remove_source_branch_after_merge      = true
  visibility_level                                           = var.visibility_level
  only_allow_merge_if_pipeline_succeeds = var.only_allow_merge_if_pipeline_succeeds
  initialize_with_readme                              = true
  template_name                                         = var.template.name
  use_custom_template                               = var.template.enabled
  group_with_project_templates_id              = var.template.group_id
  pipelines_enabled                                      = var.pipelines_enabled
  lifecycle { prevent_destroy = true }
}
```

**Comment by Stromweld** [comment] 2021-08-04 13:54
We use pretty much the same project settings as kemra102 ^^^^. Our branch protection settings then are: 
```
resource "gitlab_branch_protection" "repo_branch" {
  project                                           = gitlab_project.repository.id
  branch                                           = "main"
  push_access_level                       = "no one"
  merge_access_level                    = "developer"
  code_owner_approval_required = true
}
```
Default branch protection that gets created has push and merge access level set to maintainer. We want to be able to change those settings. This worked in 3.6.0. I've found now in 3.7.0 we get the error on initial project creation and then have to manually go in and delete the branch protection auto setup by gitlab and then rerun job to let terraform set it.

**Comment by kemra102** [comment] 2021-08-04 15:58
> This worked in 3.6.0. I've found now in 3.7.0 we get the error on initial project creation and then have to manually go in and delete the branch protection auto setup by gitlab and then rerun job to let terraform set it.

I can confirm that going back to `3.6.0` makes this issue go away, so the "offending" change was committed sometime between the releases of `3.6.0` & `3.7.0`.

**Comment by Skaronator** [comment] 2021-08-05 08:11
I can also confirm that this is a regression bug. `3.6.0` works fine while `3.7.0` has this issue.

**Comment by Stromweld** [comment] 2021-08-10 13:30
@armsnyder  is this enough to consider it a bug, or is there any suggestions on how to modify branch protection settings for default branch initialized with a readme.md file?

**Comment by armsnyder** [comment] 2021-08-10 20:49
@Stromweld It's definitely worth fixing, since it's an obvious annoyance. TBH I'm not sure it's a bug, since GitLab protects the default branch by default for you when you use it without Terraform.

I'm just waiting for an EE license renewal, but then I'll poke around and try things.

At the moment the workaround is to create the gitlab_project first, then add a gitlab_branch_protection and run`terraform import` on it.

**Comment by LipingSun** [comment] 2021-08-10 23:48
Facing the same issue. Definitely a regression in 3.7.0. Please fix soon, thanks!

**Comment by Stromweld** [comment] 2021-08-12 20:17
@armsnyder thanks for the info. Personally I think it is a bug since it did work and now it does not. I see your point about how they enable branch protection automatically without terraform, but before 3.7.0 we were able to modify the settings of that main branch protection when initialized with readme where now it causes errors. 

Having to do an import after the fact is not very terraform friendly when automating through CI/CD pipelines. Then I have to release and let it fail, manually import, and rerun deploy job to change the settings. That doesn't sound right to me. Which also makes me think of a bug as you shouldn't have to do 2 terraform runs with manual steps to properly configure things.

Only other alternative is to accept potentially unwanted defaults on main branch for maintainers and above to be able to push and merge. Or simply not maintaining main branch protection settings in code.

Can we get a more appropriate label added to this issue so that it hopefully gets prioritized higher, especially since it's affecting several users? Normally I'd lock to previous release but we desperately needed several features that were released in 3.7.0 that we are now using.

**Comment by armsnyder** [comment] 2021-08-12 20:27
I wouldn't consider it a bug if the previous behavior only worked because of the existence of another bug. But that's just semantics, I agree there should be a solution so that you can apply in one shot.

**Comment by mgriffin13** [comment] 2021-08-12 20:27
> Only other alternative is to accept potentially unwanted defaults on main branch for maintainers and above to be able to push and merge. Or simply not maintaining main branch protection settings in code.

I agree this is a bug, but my workaround is to set the `Default branch protection` to `Not protected`, and then I have a `gitlab_branch_protection` resource on the main branch with my preferred settings. This effectively accomplishes the same thing that Gitlab would have done with the `Fully protected` setting, but it's instead managed my TF.

The drawback to this is if someone creates a project outside of TF, then the default branch protection would not be set, but if you're doing everything in a Gitlab group via TF, then there shouldn't be any issues.

**Comment by Stromweld** [comment] 2021-08-12 21:49
@mgriffin13 are you using gitlab.com or host your own gitlab server? We are using gitlab.com and I'm not finding any settings at the group level for branch protection. Otherwise I do like that as a simple work around since we manage all projects via terraform.

**Comment by mgriffin13** [comment] 2021-08-12 22:06
Sorry, I'm hosting my own Gitlab server. 

This is the setting I'm talking about.. https://docs.gitlab.com/ee/user/group/#change-the-default-branch-protection-of-a-group

**Comment by Stromweld** [comment] 2021-08-12 22:30
Thanks I'll give that a try.

**Comment by mgriffin13** [comment] 2021-08-13 17:01
I would say it would be great if https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group included an option to set the `Default branch protection` policy, but that's probably a different ticket.

**Comment by Stromweld** [comment] 2021-08-13 19:06
Thanks for the tip. After 80+ groups updated the work around seems to be working well. Downside is I wasn't able to automate that change due to #667 still needing to be implemented in the provider. Hopefully this issue gets fixed and the group feature is added to help with setting all groups back to default fully protected.

**Comment by armsnyder** [comment] 2022-02-03 03:57
The active discussion on this is in #792 if folks would like to add feedback.

**Comment by Skaronator** [comment] 2022-06-04 11:51
Not stale and still an issue.

**Comment by doniz** [comment] 2022-06-08 06:54
The issue still remains. I've made a workaround to fix this as a short term solution, might be will be useful for someone too.

Using the script to delete protected branches:

```bash
terraform plan -no-color | grep -Eio "((module.*).?gitlab_branch_protection.default(\[\d\])?) (will be destroyed|must be replaced)" | awk '{print $1}' > output.txt

# Notice: for production usage remove "echo" command below to perform terraform destroy execution.
for resource in $(cat output.txt); do echo terraform destroy -target="'"$resource"'"; done

# don't forget to delete the temporary file.
rm -f output.txt

# once protected branch resources are destroyed, perform "terraform apply" to replace them.
terraform apply
```

**Comment by timofurrer** [comment] 2022-08-17 15:39
I've made a proposal for how to support this with very low effort and I'm describing the current issue in the PR in case anyone is interested in a discussion: https://github.com/gitlabhq/terraform-provider-gitlab/pull/1216

**Closed** 2022-08-21 01:53 UTC
Labels: bug, help wanted, p1

**Comment by doniz** [comment] 2022-08-25 09:40
@timofurrer Hello, I've tested it, but it works partially.

Once you want to change now either `allowed_to_merge` or `allowed_to_push` for `gitlab_branch_protection` resource, it shows the plan as expected:
![Screenshot 2022-08-25 at 12 32 41](https://user-images.githubusercontent.com/4441455/186630891-0412c91f-1dfa-45cf-a7c4-14cbb97d923f.png)

And once I confirm the deployment it shows that resources was destructed:
![Screenshot 2022-08-25 at 12 34 00](https://user-images.githubusercontent.com/4441455/186631133-27d6ad11-690a-4e3e-97d1-6afdbcdfe9f4.png)

But nothing about that was added new resources, unfortunately. So we may have to apply the plan once more to deploy the changes as the following shows that it will add a new protected branch rule:
![Screenshot 2022-08-25 at 12 34 24](https://user-images.githubusercontent.com/4441455/186631308-63a4cb84-3717-4af2-88ef-9aef39774821.png)

**Comment by timofurrer** [comment] 2022-08-25 10:48
@doniz thanks for sharing!

Can you run it with `TF_LOG=debug` and post a redacted output here?

**Comment by timofurrer** [comment] 2022-08-25 10:56
@doniz The thing with the update in `3.17.0` is that the update logic didn't change at all! Only the create logic and when it's a new resource ...

**Comment by timofurrer** [comment] 2022-08-25 14:21
@doniz I'm struggling to reproduce this. What I notice is that your "destroy" log mentions `(deposed object ...)` which AFAIK only happens because of a `create_before_destroy` lifecycle configuration. Do you have something like this present? ... or I think if there was a prior error while creating or destroying that resource. Would that ring a bell for you?

Also see this docs for reference: https://www.terraform.io/docs/glossary#deposed

**Comment by doniz** [comment] 2022-08-25 14:31
@timofurrer you directed me to the correct way. I do really have `create_before_destroy`, however not on the `gitlab_branch_protection`, but on the `gitlab_project_approval_rule` and looks like that:

```terraform
resource "gitlab_project_approval_rule" "default" {
  for_each = { for rule in var.approval_rules : rule.name => rule }
  project  = gitlab_project.default.id

  name      = each.value.name
  user_ids  = each.value.user_ids
  group_ids = each.value.group_ids

  approvals_required   = each.value.approvals_required
  protected_branch_ids = [gitlab_branch_protection.default.branch_protection_id]

  lifecycle {
    create_before_destroy = true
  }

  depends_on = [
    gitlab_branch_protection.default,
  ]
}
```

which means it depends on the `gitlab_branch_protection` and must be created first before it destroys... Ohhhh, uncommenting it just helped out. My fault. Thank you for your help 👍

**Comment by doniz** [comment] 2022-08-25 14:33
This is the output now I see:

```terraform
module.project-with-protected-branches.gitlab_branch_protection.default: Destroying... [id=38883605:master]
module.project-with-protected-branches.gitlab_branch_protection.default: Destruction complete after 1s
module.project-with-protected-branches.gitlab_branch_protection.default: Creating...
module.project-with-protected-branches.gitlab_branch_protection.default: Creation complete after 1s [id=38883605:master]
```
