### ISSUE TITLE
gitlab_project_approval_rule doesn't empty groups/users when switching between them

### ISSUE THREAD

**Issue by QuingKhaos** [gitlabhq/terraform-provider-gitlab#755] opened 2021-11-24 18:10 UTC
### Terraform Version

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.8.0
```

### Affected Resource(s)

- `gitlab_project_approval_rule`

### Terraform Configuration Files

I've created a run-able example as a snippet here: https://gitlab.com/khaossolutions/gitops/infra/terraform/terraform-gitlab-project/-/snippets/2211612

```terraform
locals {
  group_ids = [for group in data.gitlab_group.example : group.id]
  user_ids  = [for user in data.gitlab_user.example : user.id]
}

resource "gitlab_project_approval_rule" "example" {
  project = data.gitlab_project.example.id
  name    = "SSCCE Example"

  group_ids = var.approvers == "groups" ? local.group_ids : []
  user_ids  = var.approvers == "users" ? local.user_ids : []

  approvals_required = 1
}
```

### Debug Output

The debug output, including a snippet for the relevant output can be found here: https://gitlab.com/khaossolutions/gitops/infra/terraform/terraform-gitlab-project/-/snippets/2211674

### Expected Behavior

The `gitlab_project_approval_rule` should remove the groups from the merge request approval rule, while adding the users

### Actual Behavior

The groups are not removed from the merge request approval rule. If you look at the relevant part of the log output, the PUT request only includes `user_ids` sent.

### Steps to Reproduce

1. Clone the example snippet
1. Adapt the `terraform.tfvars` with an existing project, groups and users to test against.
1. Init the backend and provider with `terraform init` (uses a local state backend).
1. Create the example merge request approval rule with `terraform apply`.
1. Verify the merge request approval rule was created in the project settings.
1. Run `terraform apply -var="approvers=users"` to remove the groups from the merge request approval rule and add the users to it.
1. Verify with `terraform plan -var="approvers=users"` and in the project settings, that the groups are still part of the merge request approval rule.
1. Taint the merge request approval rule with `terraform taint gitlab_project_approval_rule.example` to force re-creation.
1. Re-run `terraform apply -var="approvers=user"` to re-create the approval rule with the users only.
1. Verify with `terraform plan -var="approvers=user"` and in the project settings, that only the users are part of the merge request approval rule.
1. Run `terraform destroy` to cleanup the example merge request approval rule.

### Important Factoids

The same behavior can be observed if you reproduce the example in the other direction switching from users to groups. When having more than one group/user in the approval rule, removing one of them works. Removing all of doesn't work, it's not possible to empty the `group_ids`/`user_ids`.

This issue arises when a `gitlab_project_approval_rule` already exists within Terraform and you want to change from using only groups to using only users or vice-versa in the project-level merge request approval rules. Thus, this a problem with updating the resource.

While diving deeper into the code, it seems to be problem with the APIs Go SDK, which omits empty user/group IDs fields:

```go
// UpdateProjectLevelRuleOptions represents the available UpdateProjectApprovalRule()
// options.
//
// GitLab API docs:
// https://docs.gitlab.com/ee/api/merge_request_approvals.html#update-project-level-rule
type UpdateProjectLevelRuleOptions struct {
	ApprovalsRequired  *int    `url:"approvals_required,omitempty" json:"approvals_required,omitempty"`
	GroupIDs           []int   `url:"group_ids,omitempty" json:"group_ids,omitempty"`
	Name               *string `url:"name,omitempty" json:"name,omitempty"`
	ProtectedBranchIDs []int   `url:"protected_branch_ids,omitempty" json:"protected_branch_ids,omitempty"`
	UserIDs            []int   `url:"user_ids,omitempty" json:"user_ids,omitempty"`
}
```

Manually running the update request with an empty `group_ids` removes the groups.

```
PUT https://gitlab.com/api/v4/projects/26271222/approval_rules/1110757
Content-Type: application/json
Authorization: Bearer {{GITLAB_TOKEN}}

{
  "approvals_required": 1,
  "name": "SSCCE Example",
  "group_ids": [],
  "user_ids": [
    8802994,
    602331
  ]
}
```

### References

- #694 - but can't say for sure if this is related as the issue contains way too less context.
- xanzy/go-gitlab#1292 - the possible root issue
- xanzy/go-gitlab#1295 - BC announcement
- xanzy/go-gitlab#1294 - PR with BC, but may fix this underlying problem and similar ones in other cases

**Comment by QuingKhaos** [comment] 2021-11-24 19:21
### Escape Hatch

And here it is, the heavy bash/jq-fu if you don't want to taint (re-create) every approval rule. I use [glab](https://glab.readthedocs.io/en/latest/) to call the API, but you can rewrite it to use curl too.

Basically I update every approval rule from the current plan to remove all groups as intended. I don't have the name or number of approvers available from my plan jq-fu, so I just set them to arbitrary values, which will then be reconciled with a new `terraform apply` run.

Ensure in the `terraform plan` only changes to the approval rules are present, as the jq-fu doesn't really take care about what change there is in the plan.

```bash
$ terraform plan -out=plan.cache && terraform show -json plan.cache | jq -r '[.resource_changes[]?.change] | flatten | map(select(.actions[]=="update")) | .[].before.id' | xargs -I{} -n1 -t sh -c 'project_id="$(echo {} | cut -d: -f1)"; rule_id="$(echo {} | cut -d: -f2)"; glab api -X PUT projects/${project_id}/approval_rules/${rule_id} -F name=update-me -F approvals_required=1 -F group_ids=[]'

**Comment by armsnyder** [comment] 2022-02-04 01:11
Thanks for the research on this. Since https://github.com/xanzy/go-gitlab/pull/1294 was merged, we could probably fix this now.

**Comment by timofurrer** [comment] 2022-02-09 08:22
I was able to observe the expected behavior using the latest provider (>= 3.9). 

As @armsnyder mentioned, this is because we've upgraded go-gitlab (see #805) and there we always send an empty `group_ids` / `user_ids` set if it hasn't been specified or is explicitly empty.

I'm going to close this. Let us know in case you are still facing issues 🎉

**Closed by timofurrer** 2022-02-09 08:22 UTC
Labels: bug
