### ISSUE TITLE
Gitlab Groups Behavior Change

### ISSUE THREAD

**Issue by josjaf** [gitlabhq/terraform-provider-gitlab#159] opened 2019-07-03 02:53 UTC
Terraform v0.12.3
+ provider.gitlab v2.2.0

Terraform stopped supporting groups it looks like. 
```
Error: Unsupported argument

  on shared_group.tf line 18, in resource "gitlab_project" "normandy":
  18:     shared_with_groups = {

An argument named "shared_with_groups" is not expected here. Did you mean to
define a block of type "shared_with_groups"?
```

for code:
```resource "gitlab_project" "normandy" {
    name = "normandy"
    default_branch = "master"
    shared_with_groups = [
    {
        group_id = "${gitlab_group.aws_newport.id}"
        group_access_level = "developer"
    },
    {
        group_id = "${gitlab_group.examples.id}"
        group_access_level = "developer"
    }
    ]

}
```

**Comment by pdecat** [comment] 2019-07-03 12:45
With terraform 0.12+, it's needs to be defined as blocks:

```
    shared_with_groups {
        group_id = "${gitlab_group.aws_newport.id}"
        group_access_level = "developer"
    }

    shared_with_groups {
        group_id = "${gitlab_group.examples.id}"
        group_access_level = "developer"
    }
```

**Comment by josjaf** [comment] 2019-07-03 13:36
Well in this case, I have a list of blocks, how can I do that now?

**Comment by pdecat** [comment] 2019-07-03 14:59
Do you mean you need to pass the list as a variable?

In that case, you should use `for_each` with dynamic blocks, e.g.:

```
  dynamic "shared_with_groups" {
    for_each = var.groups
    content {
        group_id = shared_with_groups.value.group_id
        group_access_level = shared_with_groups.value.group_access_level
    }
  }
```

**Comment by josjaf** [comment] 2019-07-11 00:41
No I need to make something like this work - this was working fine for me for a while

```
resource "gitlab_project" "repo1" {
    name = "repo1"
    default_branch = "master"
    shared_with_groups = [
    {
        group_id = "${gitlab_group.repo3.id}"
        group_access_level = "developer"
    },
    {
        group_id = "${gitlab_group.examples.id}"
        group_access_level = "developer"
    }
    ]

}
```

**Comment by pdecat** [comment] 2019-07-11 06:49
You can no longer use that syntax with terraform 0.12+, you have to statically repeat the blocks or use the dynamic syntax.

**Comment by flelli** [comment] 2019-11-19 10:56
Even with this syntax is not working:

```
dynamic "shared_with_groups" {
    for_each = var.share_with_groups
    content {
      group_id              = shared_with_groups.key
      group_access_level    = shared_with_groups.value
    }
  }
```

It applies with no errors but it has no effect (the share is not visible from GitLab's UI) and is not retained in the Terraform state (any subsequent plan or apply detects it as a new change).

**Comment by armsnyder** [comment] 2020-09-12 23:45
@josjaf Did the comments here help you with this issue? Can we close this?

@flelli I was able to use the dynamic syntax successfully when I tried to reproduce this:

```terraform
locals {
  groups = [{id: 8}]
}

resource "gitlab_project" "project" {
  name = "my-project"
  visibility_level = "private"
  dynamic "shared_with_groups" {
    for_each = local.groups
    content {
      group_id = shared_with_groups.value["id"]
      group_access_level = "developer"
    }
  }
}
```

**Comment by josjaf** [comment] 2020-09-13 00:18
No, it didnt work. I didn't want to create an organization because it would
mean that I have to leave my existing organization.

**Comment by armsnyder** [comment] 2020-09-13 00:24
@josjaf My understanding of this issue is that it is about a change in the version of Terraform you are using (0.12), not a change to this provider plugin. Would you agree? As others have pointed out the syntax of Terraform was changed to this:

```terraform
resource "gitlab_project" "repo1" {
  name           = "repo1"
  default_branch = "master"

  shared_with_groups {
    group_id           = gitlab_group.repo3.id
    group_access_level = "developer"
  }

  shared_with_groups {
    group_id           = gitlab_group.examples.id
    group_access_level = "developer"
  }
}
```

**Comment by josjaf** [comment] 2020-09-13 00:38
Ah sorry, I was thinking of an issue I had with github, let me check and
get back to you.

**Comment by armsnyder** [comment] 2021-01-25 08:52
Hi. I'm closing this issue since it's been silent for awhile and it really appears like it's a Terraform syntax thing, but let me know if you find out that we need to re-open it, and I'd be happy to.

**Closed by armsnyder** 2021-01-25 08:52 UTC
Labels: question
