### ISSUE TITLE
Unauthorized error using 3.8.0 provider

### ISSUE THREAD

**Issue by jamestenglish** [gitlabhq/terraform-provider-gitlab#753] opened 2021-11-19 14:50 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

The provider 3.8.0 introduces breaking changes for auth, it doesn't appear that a PAT works as a bearer token:

With `PRIVATE-TOKEN`:

```bash
$ curl --header "PRIVATE-TOKEN: REDACTED" "REDACTED/api/v4/user" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   928  100   928    0     0   2636      0 --:--:-- --:--:-- --:--:--  2628
{
  "id": 22,
   ...
```

with bearer:

```bash
$ curl --header "Authorization: Bearer REDACTED" "REDACTED/api/v4/user" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30  100    30    0     0     62      0 --:--:-- --:--:-- --:--:--    62
{
  "message": "401 Unauthorized"
}
```

**Comment by QuingKhaos** [comment] 2021-11-24 16:39
What is the version of the GitLab instance you're running this against?

PATs as bearer token are working on gitlab.com, and I don't know what version ago the support for this was introduced. Even the [docs for 12.10](https://docs.gitlab.com/12.10/ee/api/index.html#personal-access-tokens) are listing this as supported.

**Comment by timofurrer** [comment] 2022-01-26 09:04
This is most certainly caused by an ancient GitLab instance or an invalid PAT - and therefore not a bug in the provider. For the lack of a response from the author I'm going to close this issue for now. 🎉

**Closed by timofurrer** 2022-01-26 09:04 UTC
