### ISSUE TITLE
gitlab_deploy_token does not work on gitlab.com

### ISSUE THREAD

**Issue by krotscheck** [gitlabhq/terraform-provider-gitlab#507] opened 2020-12-16 14:18 UTC
### Terraform Version
```
Terraform v0.14.2
+ provider registry.terraform.io/gitlabhq/gitlab v3.3.0
```

### Affected Resource(s)
- gitlab_deploy_token

### Terraform Configuration Files
```hcl
resource "gitlab_group" "dataplay" {
  name = "dataplay-io"
  path = "dataplay-io"
  description = "Source repositories for dataplay.io"
  visibility_level = "private"
  lfs_enabled = true
}

resource "gitlab_deploy_token" "dp" {
  name = "dataplay_checkout"
  username = "dataplay_checkout"
  expires_at = "0001-01-01T00:00:00Z"
  group = gitlab_group.dataplay.id
  scopes = [
    "read_repository",
    "read_registry"
  ]
}
```

### Debug Output
```
gitlab_deploy_token.test: Creating...
gitlab_deploy_token.test: Creation complete after 0s [id=306826]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
Releasing state lock. This may take a few moments...
```

### Panic Output
No panic.

### Expected Behavior
The deploy token is created, visible in the gitlab UI, and able to check out resources.

### Actual Behavior
Resource has been created and managed, but is not visible in the UI, nor can it be used to check out resources.
```
Active Deploy Tokens (0)

                        This group has no active Deploy Tokens.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
Running against gitlab.com

**Comment by armsnyder** [comment] 2021-01-25 08:07
@krotscheck If you're able to attach a gist with your Terraform debug output, that would help a lot as we would be able to inspect the HTTP response.

**Comment by estei** [comment] 2021-03-22 14:19
I ran into this issue today when trying to create a project deploy token.

Running TF with debug on gave me a line that looked a bit suspect (notice the `%2f`s)

```
2021-03-22T13:59:43.789+0100 [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: ---[ REQUEST ]---------------------------------------
2021-03-22T13:59:43.789+0100 [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: POST /api/v4/projects/ds-api%2Finfrastructure%2Flive%2Fclusters%2Fcluster-services/deploy_tokens HTTP/1.1
2021-03-22T13:59:43.789+0100 [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Host: gitlab.com
```

Looking at the [api documentation](https://docs.gitlab.com/ee/api/resource_access_tokens.html) it mentions an ID not necessarily a path as the [provider documentation implies](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/deploy_token)

I found the the ID of the project on gitlab.com and tried supplying that instead of the path and I now have a deploy token generated by Terraform. I am guessing the reason the ID works where the path does not has something to do with escaping of the path value.

Funny though that the API returns a nice 201 created even if it has not created the token on the intended project. So there might be something to look into on the API end also. Maybe the API is generating orphan tokens somewhere.

## Workarounds

Find the Project ID in the UI on gitlab.com and use this instead of the path.

or if you do not want to bind yourself to the numeric id, use a data source.

```
data "gitlab_project" "example_project" {
    id = "path/to/the/project"
}

resource "gitlab_deploy_token" "example_token" {
  project    = data.gitlab_project.example_project.id
  name       = "example"
  scopes = [ "read_repository" ]
}
```

**Comment by timofurrer** [comment] 2022-02-08 19:20
@krotscheck  when I tried to reproduce your issue with the terraform code you've provided I have the same behavior. However, the reason for that seems to be the `expires_at` date, which is way in the past and therefore I can only assume that GitLab is not listing it in the `Active Deploy Tokens` section, because it's in fact not active, but expired.

Using a timestamp in the future correctly shows the token.

@estei I'm unable to reproduce the issue you are describing. I'm assuming that it has either been fixed in the latest GitLab releases or in the provider.
Since it seems to be unrelated to the initial report here I suggest that if you still facing that issue that you create a new issue.

I'm going to close this. @krotscheck In case you are still facing that issue with an `expires_at` date in the future, please let us know and we'll re-open this 🎉

**Closed by timofurrer** 2022-02-08 19:20 UTC
Labels: bug, question, p2
