### ISSUE TITLE
gitlab_project_share_group is not persistent

### ISSUE THREAD

**Issue by stackexpress-shivam** [gitlabhq/terraform-provider-gitlab#312] opened 2020-05-18 11:23 UTC
### Terraform Version
Terraform v0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project
- gitlab_project_share_group

### Terraform Configuration Files
```hcl
resource "gitlab_project" "project1" {
    name                            = "project1"
    visibility_level                = "private"
    container_registry_enabled      = true
    issues_enabled                  = true
    wiki_enabled                    = true
}

resource "gitlab_project_share_group" "project1-admin" {
    project_id            = gitlab_project.project1.id
    group_id              = "5458672"
    access_level          = "maintainer"
}

resource "gitlab_project_share_group" "project1-dev" {
    project_id            = gitlab_project.project1.id
    group_id              = "5317123"
    access_level          = "developer"
}

```

### Expected Behavior
The resource sharing should be persistent during all future runs.

### Actual Behavior
The sharing is disabled on very next run:

```bash
terraform plan

  # gitlab_project.project1 will be updated in-place
  ~ resource "gitlab_project" "project1" {
        approvals_before_merge                           = 0
        archived                                         = false
        container_registry_enabled                       = true
        http_url_to_repo                                 = "https://gitlab.com/test/project1.git"
        id                                               = "1212121212"
        issues_enabled                                   = true
        lfs_enabled                                      = true
        merge_method                                     = "merge"
        merge_requests_enabled                           = true
        name                                             = "project1"
        namespace_id                                     = 12121212
        only_allow_merge_if_all_discussions_are_resolved = false
        only_allow_merge_if_pipeline_succeeds            = false
        path                                             = "project1"
        pipelines_enabled                                = true
        request_access_enabled                           = true
        runners_token                                    = "xxxxxxxxxxx"
        shared_runners_enabled                           = false
        snippets_enabled                                 = true
        ssh_url_to_repo                                  = "git@gitlab.com:test/project1.git"
        tags                                             = []
        visibility_level                                 = "private"
        web_url                                          = "https://gitlab.com/test/project1"
        wiki_enabled                                     = true

      - shared_with_groups {
          - group_access_level = "developer" -> null
          - group_id           = 131313 -> null
          - group_name         = "group-name2" -> null
        }
      - shared_with_groups {
          - group_access_level = "maintainer" -> null
          - group_id           = 121212 -> null
          - group_name         = "group-name1" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by stackexpress-shivam** [comment] 2020-05-18 11:26
It tries to delete the `shared_with_groups` resources when I run 
terraform plan or terraform apply

**Comment by Binsabbar** [comment] 2020-05-29 21:57
I am having the same issue. I think there is also an open issue already. I really needed to use `resource "gitlab_project_share_group"` so my way around for now was to use `lifecycle` in the project resource to ignore certain attributes. I do not like it this way, but it does the job I need at least for now.
```
resource "gitlab_project" "my_project" {
  name                   = "my-project”
  lifecycle {
    ignore_changes  = [shared_with_groups]
    prevent_destroy = true
  }
}
```

**Comment by armsnyder** [comment] 2020-09-13 03:55
Closing this as a duplicate of #219. I've recently reproduced the problem.

**Closed by armsnyder** 2020-09-13 03:55 UTC
