### ISSUE TITLE
Resource 'gitlab_project_protected_environment' option 'deploy_access_levels' continuously applies

### ISSUE THREAD

**Issue by ixolt** [gitlabhq/terraform-provider-gitlab#1273] opened 2022-10-11 02:04 UTC
### GitLab Provider version

3.18.0

### GitLab version

Gitlab Ultimate

### Terraform version

1.3.1

### Relevant Terraform Configuration

```hcl
resource "gitlab_project_environment" "devops-infra" {
  project      = module.devops-infra.project_id
  name         = "example"
  external_url = "https://www.example.com"
}

resource "gitlab_project_protected_environment" "example_with_access_level" {
  project                 = module.devops-infra.project_id
  required_approval_count = 1
  environment             = gitlab_project_environment.devops-infra.name

  deploy_access_levels {
    access_level = "developer"
  }
  deploy_access_levels {
    access_level = "maintainer"
  }
}
```

### Relevant log output

```shell
# gitlab_project_protected_environment.example_with_access_level must be replaced
-/+ resource "gitlab_project_protected_environment" "example_with_access_level" {
      ~ id                      = "*********:example" -> (known after apply)
        # (3 unchanged attributes hidden)

      ~ deploy_access_levels {
          ~ access_level             = "maintainer" -> "developer" # forces replacement
          ~ access_level_description = "Maintainers" -> (known after apply)
          - group_id                 = 0 -> null
          - user_id                  = 0 -> null
        }
      ~ deploy_access_levels {
          ~ access_level             = "developer" -> "maintainer" # forces replacement
          ~ access_level_description = "Developers + Maintainers" -> (known after apply)
          - group_id                 = 0 -> null
          - user_id                  = 0 -> null
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Description

Because API `https://gitlab.com/api/v4/projects/****/protected_environments` returns a list of deploy_access_levels in format "Last at first". Terraform will try to apply these changes continuously

applied changes
```
  deploy_access_levels {
    access_level = "developer"
  }
  deploy_access_levels {
    access_level = "maintainer"
  }
```
in plan after apply

```
~ deploy_access_levels {
    ~ access_level             = "maintainer" -> "developer" # forces replacement
    ...
  }
~ deploy_access_levels {
    ~ access_level             = "developer" -> "maintainer" # forces replacement
    ...
  }
```

It is the same for access_level, users_id, and group_id.
It might require changes to GitLab API.

**Comment by timofurrer** [comment] 2022-10-14 12:16
Duplicate of #1266

**Closed by timofurrer** 2022-10-14 12:16 UTC
Labels: needs-triage
