### ISSUE TITLE
Terraform destroy archieves gitlab project.

### ISSUE THREAD

**Issue by RastogiAbhijeet** [gitlabhq/terraform-provider-gitlab#268] opened 2020-02-28 06:36 UTC
### Terraform Version
v 0.12.18
### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project

### Terraform Configuration Files
```
provider "gitlab" {
  token = var.gitlab_token
}

data "gitlab_group" "block8" {
  group_id = var.gitlab_group_id
}

resource "gitlab_project" "block8" {
  name         = var.gitlab_project_name
  namespace_id = data.gitlab_group.block8.id
}
```

### Expected Behavior
`terraform destroy should have delete the gitlab project`

### Actual Behavior
`terraform destroy archieved the project.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
Once the project is successfully created. Run the following command.

2. `terraform destroy`

**Comment by ilpianista** [comment] 2020-03-09 15:20
Isn't this a duplicate of #263?

**Comment by ringods** [comment] 2020-04-01 08:45
@RastogiAbhijeet did you experience this against a Gitlab setup with a paid license? From a certain tier, Gitlab activates soft delete as described in #263 and then that is expected behaviour on the Gitlab side which we can't do anything about on the Terrform provider side.

**Comment by ringods** [comment] 2020-05-30 07:22
Hello @RastogiAbhijeet, can you please verify? Without any answer, I will assume it was the `soft-delete` behaviour you saw in action and mark this ticket as closed. This in a new Gitlab feature introduced in the Gitlab v12 version series.

**Comment by armsnyder** [comment] 2020-09-13 02:08
Closing this since it seems to be working as intended.

**Closed by armsnyder** 2020-09-13 02:08 UTC
