### ISSUE TITLE
Provider throw error when using

### ISSUE THREAD

**Issue by sherrera-hx** [gitlabhq/terraform-provider-gitlab#687] opened 2021-08-04 14:36 UTC
Hi all, we are trying to use the latest version and we are having the following issue

![image](https://user-images.githubusercontent.com/73550939/128200199-0f617346-f09d-485b-b7af-64934fd17dfa.png)

**Comment by Stromweld** [comment] 2021-08-09 22:11
it doesn't look like you are using the latest version. Latest is 3.7.0 and your output says you are using 3.5.0. Check versions files that may be locking it or setting version ceiling or any terraform blocks with required providers option set for gitlab provider and version 3.5.0.

**Comment by timofurrer** [comment] 2022-01-26 09:11
@sherrera-hx can you please provide a little bit more information about what you are trying to do? Some terraform code, so that we can reproduce it? Anyways, using the latest release, do you still experience that issue?

**Comment by timofurrer** [comment] 2022-02-24 09:26
Since the report is from a quite outdated (3.5.0) provider release and there hasn't been any response within a month, I'm going to close this. Please open a new issue in case you are experiencing similar issues with an up-to-date provider release :)

**Closed by timofurrer** 2022-02-24 09:26 UTC
Labels: waiting-response
