### ISSUE TITLE
Feature Request: instance wide deploy keys

### ISSUE THREAD

**Issue by whoracle** [gitlabhq/terraform-provider-gitlab#733] opened 2021-10-21 09:08 UTC
Feature Request Details

Please consider adding a standalone resource for instance wide deploy keys or functionality to bind gitlab_deploy_key to the instance instead of to a project.
This might need the can_push functionality in gitlab_deploy_key_enable.

Thanks!

**Comment by armsnyder** [comment] 2022-01-22 22:57
Closing as a duplicate of #373

**Closed by armsnyder** 2022-01-22 22:58 UTC
