### ISSUE TITLE
[Issue] Сouldn't find a GitLab user, version 3.9.1

### ISSUE THREAD

**Issue by big-bag** [gitlabhq/terraform-provider-gitlab#857] opened 2022-02-09 15:53 UTC
### Terraform Version
1.1.5

### Affected Resource(s)
List of the resources:
- gitlab_user

### Terraform Configuration Files
`main.tf`
```hcl
terraform {
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.9.1"
    }
  }
}

provider "gitlab" {
  token = var.gitlab_token
}

locals {
  users = [
    "username@domain.com"
  ]
}

data "gitlab_user" "gitlab_user" {
  for_each = toset(local.users)

  email = each.key
}
```

### Error Output
https://gist.github.com/big-bag/5a1fa6240fef04543ce21dc780eb6145

### Expected Behavior
Terraform will receive information about users in GitLab.

### Actual Behavior
![изображение](https://user-images.githubusercontent.com/29428735/153232261-753b6485-e99e-4daf-b24b-8517e322d4cb.png)

### Steps to Reproduce
Steps required to reproduce the issue:
- `terraform plan`

### Important Factoids
1. We use Terraform Cloud
2. We log in to GitLab through Google using SAML

**Comment by timofurrer** [comment] 2022-02-09 15:57
I suspect that you've also run into 

* https://github.com/gitlabhq/terraform-provider-gitlab/issues/839

GitLab changed in the recent versions that you can only lookup users by their "public email" and not their "primary email" address.

I'm going to close this.

Duplicate of #839

**Closed by timofurrer** 2022-02-09 15:57 UTC
Labels: needs-triage
