### ISSUE TITLE
[Feature Request] Ability to enable merged results pipeline and merged train

### ISSUE THREAD

**Issue by Alfredo-Moreira** [gitlabhq/terraform-provider-gitlab#681] opened 2021-07-30 17:26 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:

- gitlab_project

Provide ability to set Merged Results Pipeline and Merge Train toggles.

![Screen Shot 2021-07-30 at 11 21 56 AM](https://user-images.githubusercontent.com/11844106/127689836-e8680afe-ceec-4f06-9f6b-0d2dd9488b19.png)

## NOTE ##
According to [Gitlab.go project file](https://github.com/xanzy/go-gitlab/blob/master/projects.go)  no property for Merge results or Merge train has been created yet. I will update the issue once property is available for integration.

### UPDATE ###
Request created in Project to add support https://github.com/xanzy/go-gitlab/issues/1185

**Comment by armsnyder** [comment] 2021-07-30 19:18
Duplicate of #623

**Closed by armsnyder** 2021-07-30 19:18 UTC
