### ISSUE TITLE
Panic when applying gitlab_branch_protection when existing protection have no role for push or merge access level.

### ISSUE THREAD

**Issue by VMitov** [gitlabhq/terraform-provider-gitlab#415] opened 2020-09-15 12:48 UTC
Hi there,

I'm trying to enforce a protection of the "master" branch for a couple of repositories. If there is existing protection with no role for either "Allowed to merge" or "Allowed to push" (possible trough the UI) - applying gitlab_branch_protection for that project fails with panic. 

### Terraform Version
Terraform v0.13.2
+ provider registry.terraform.io/-/gitlab v2.11.0
+ provider registry.terraform.io/terraform-providers/gitlab v2.11.0

### Affected Resource(s)
- gitlab_branch_protection

### Terraform Configuration Files
```hcl
resource "gitlab_branch_protection" "branch_protection" {
  project            = "1"
  branch             = "master"
  push_access_level  = "no one"
  merge_access_level = "developer"
}
```

### Panic Output
https://gist.github.com/VMitov/bcb881e2e638eb998c99c668aca56c22

### Expected Behavior
Successful apply.

### Actual Behavior
Panic.

### Steps to Reproduce
1. Create manually a protected branch with an empty "Allowed to merge" role. 
2. Create a Terraform resource for that branch protection.
3. `terraform apply`

**Comment by hobti01** [comment] 2021-04-01 16:33
We are still seeing this with version v3.5.0

```
2021-04-01T16:12:51.715Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 2021/04/01 16:12:51 [DEBUG] read gitlab branch protection for project **redacted**, branch master
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 2021/04/01 16:12:51 [DEBUG] GitLab API Request Details:
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: ---[ REQUEST ]---------------------------------------
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: GET /api/v4/projects/24308282/protected_branches/master HTTP/1.1
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Host: gitlab.com
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: User-Agent: HashiCorp Terraform/0.12.29 (+https://www.terraform.io) Terraform Plugin SDK/1.15.0 terraform-provider-gitlab
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Accept: application/json
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Private-Token: **redacted**
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Accept-Encoding: gzip
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 
2021-04-01T16:12:51.721Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: -----------------------------------------------------
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 2021/04/01 16:12:51 [DEBUG] GitLab API Response Details:
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: ---[ RESPONSE ]--------------------------------------
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: HTTP/2.0 200 OK
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Cache-Control: max-age=0, private, must-revalidate
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Cf-Cache-Status: DYNAMIC
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Cf-Ray: 639319fb3d5afafa-DUS
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Cf-Request-Id: 092fce91020000fafa8f806000000001
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Content-Type: application/json
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Date: Thu, 01 Apr 2021 16:12:52 GMT
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Etag: W/"da39f5e8df1a0f12437f5ddb58baeb68"
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Gitlab-Lb: fe-10-lb-gprd
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Gitlab-Sv: localhost
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Ratelimit-Limit: 2000
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Ratelimit-Observed: 1139
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Ratelimit-Remaining: 860
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Ratelimit-Reset: 1617293632
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Ratelimit-Resettime: Thu, 01 Apr 2021 16:13:52 GMT
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Referrer-Policy: strict-origin-when-cross-origin
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Server: cloudflare
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Set-Cookie: __cfduid=dddda48f19b1d31bdd98900ae6bda2d9b1617293572; expires=Sat, 01-May-21 16:12:52 GMT; path=/; domain=.gitlab.com; HttpOnly; SameSite=Lax; Secure
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Strict-Transport-Security: max-age=31536000
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Vary: Accept-Encoding
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: Vary: Origin
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: X-Content-Type-Options: nosniff
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: X-Frame-Options: SAMEORIGIN
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: X-Gitlab-Feature-Category: source_code_management
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: X-Request-Id: 01F273AYDATGVJ14BKEGXG060K
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: X-Runtime: 0.049503
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: {
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "id": 35578735,
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "name": "master",
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "push_access_levels": [],
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "merge_access_levels": [
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:   {
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:    "access_level": 30,
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:    "access_level_description": "Developers + Maintainers",
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:    "user_id": null,
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:    "group_id": null
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:   }
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  ],
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "allow_force_push": false,
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "unprotect_access_levels": [],
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0:  "code_owner_approval_required": false
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: }
2021-04-01T16:12:51.746Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: -----------------------------------------------------
2021-04-01T16:12:51.748Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: panic: runtime error: index out of range [0] with length 0
2021-04-01T16:12:51.748Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 
2021-04-01T16:12:51.748Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: goroutine 13728 [running]:
2021-04-01T16:12:51.748Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/gitlabhq/terraform-provider-gitlab/gitlab.resourceGitlabBranchProtectionRead(0xc000123500, 0x109b1c0, 0xc0002b8000, 0xc000123500, 0x0)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/gitlabhq/terraform-provider-gitlab/gitlab/resource_gitlab_branch_protection.go:120 +0x73c
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003739e0, 0xc00007eaf0, 0x109b1c0, 0xc0002b8000, 0xc0005170a0, 0x0, 0x0)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:460 +0x129
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ed50, 0x12e31a0, 0xc00098e030, 0xc00078ae40, 0xc00000ed50, 0xc00098e030, 0xc0005b2b78)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:525 +0x3dd
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x1103140, 0xc00000ed50, 0x12e31a0, 0xc00098e030, 0xc00078ade0, 0x0, 0x12e31a0, 0xc00098e030, 0xc0007eedc0, 0xad)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00050a600, 0x12ec720, 0xc000580780, 0xc000909a00, 0xc000502540, 0x18c88d0, 0x0, 0x0, 0x0)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).handleStream(0xc00050a600, 0x12ec720, 0xc000580780, 0xc000909a00, 0x0)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:1313 +0xd34
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000582120, 0xc00050a600, 0x12ec720, 0xc000580780, 0xc000909a00)
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:722 +0xa5
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-04-01T16:12:51.749Z [DEBUG] plugin.terraform-provider-gitlab_v3.5.0: 	google.golang.org/grpc@v1.27.1/server.go:720 +0xa5
2021-04-01T16:12:51.752Z [DEBUG] plugin: plugin process exited: path=/var/run/terraform/.terraform/plugins/linux_amd64/terraform-provider-gitlab_v3.5.0 pid=7231 error="exit status 2"
```

The request using the same private token with curl does not have the same response:
```
$ curl -sSf --header "Authorization: Bearer $GITLAB_REST_API_TOKEN" "https://gitlab.com/api/v4/projects/$PROJECT_ID/protected_branches/master" | jq
{
  "id": 33554219,
  "name": "master",
  "push_access_levels": [
    {
      "access_level": 0,
      "access_level_description": "No one",
      "user_id": null,
      "group_id": null
    }
  ],
  "merge_access_levels": [
    {
      "access_level": 30,
      "access_level_description": "Developers + Maintainers",
      "user_id": null,
      "group_id": null
    }
  ],
  "allow_force_push": false,
  "unprotect_access_levels": [
    {
      "access_level": 40,
      "access_level_description": "Maintainers",
      "user_id": null,
      "group_id": null
    }
  ],
  "code_owner_approval_required": false
}
```

It's very curious that the ID for the `protected_branches` resource is not the same in the debug output and the curl output  although both requests are for the same project id and branch.

**Comment by beekeep** [comment] 2022-03-25 21:49
Hi @VMitov & @hobti01 !   I am attempting to reproduce this with the latest version (3.12.0) and I am not having much luck.  
Here is what I tried:

```
terraform {
  required_version = ">= 0.15"

  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.12.0"
    }
  }
}

resource "gitlab_project" "project" {
  name             = "Panic Test"
  description      = "Test panic issue"
  visibility_level = "public"
}

resource "gitlab_branch_protection" "branch_protection" {
  project            = gitlab_project.project.id
  branch             = "master"
  push_access_level  = "no one"
  merge_access_level = "developer"
}
```

Please let me know if I don't have the correct configuration! 😃

**Comment by timofurrer** [comment] 2022-08-19 15:48
@hobti01 I've just checked and the index access which caused the panic doesn't exist anymore in the few latest provider releases. And instead it actually checks if there is at least one level and would only then use it.

My best guess is that this is resolved - therefore and because there hasn't been any activity after Marks question, I'm taking the liberty to close this :) In case you run into this problem again with the latest provider release - please let us know and we can re-open or feel free to create a new issue!

Thanks 🤝

**Closed by timofurrer** 2022-08-19 15:48 UTC
Labels: bug, p2
