### ISSUE TITLE
Feature request - Allow Terraform to add custom domains to Pages

### ISSUE THREAD

**Issue by tangodev** [gitlabhq/terraform-provider-gitlab#500] opened 2020-12-02 17:30 UTC
Currently adding your own domain to Pages requires a manual setup.

### Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/gitlabhq/gitlab v3.3.0
```

### Affected Resource(s)

- gitlab_project

### Expected Behavior
Jane is working on her static site and wants to use Pages to host it. Pages requires her to add a domain, `example.com`. Jane should be able to add a Terraform resource and have Terraform add the domain to that Pages instance.

### Actual Behavior
Jane has to go to Pages and manually add `example.com` which is error prone and unnecessary, since `example.com` is already defined in her variables and could be added programatically.

![image](https://user-images.githubusercontent.com/12778629/100903815-9e5d0f80-34c6-11eb-9f56-6b496245f70f.png)

### References

- https://github.com/gitlabhq/terraform-provider-gitlab/issues/498
- [Adding a custom domain to Pages](https://docs.gitlab.com/ee/user/project/pages/custom_domains_ssl_tls_certification/index.html#set-up-pages-with-a-custom-domain)

**Comment by armsnyder** [comment] 2021-01-25 08:43
I'm closing this as a duplicate of #498, since it sounds like this would also be resolved by the addition of a new `project_pages_domain` resource. Keeping the discussion for a new resource in one issue helps us be organized. 😉

**Closed by armsnyder** 2021-01-25 08:43 UTC
