### ISSUE TITLE
When gitlab_project is created, there is always a default protected branch, it cannot be managed by Terraform from the box.

### ISSUE THREAD

**Issue by LDVSOFT** [gitlabhq/terraform-provider-gitlab#749] opened 2021-11-16 19:33 UTC
When I want to create a `gitlab_project` with non-default branch protection, I can trivially add more branches to be protected in any way I wanted with `gitlab_branch_protection`, except for the default branch. I cannot delete or manipulate it without importing it into the Terraform state for some `gitlab_branch_protection` resource first, so I cannot do this in one clean Terraform run.

### Terraform Version
Terraform 1.0.5. GitLab provider 3.7.0.

### Affected Resource(s)
- `gitlab_project`
- `gitlab_branch_protection`

### Expected Behavior
`gitlab_project` created via Terraform should either don't have any default branch protection, or rather provide an option not to create one. It may be emulated provider-side, like `aws_security_group` do: AWS provider removes default rules from the new group.

### Actual Behavior
Every created `gitlab_project` has a default branch protected, I cannot specify Terraform configuration to change/delete it without manual intervention (i.e. import or doing it manually) for each project affected.

Since I use Terraform to create GitLab repos for an university course, there are quite a lot of repositories =(

### Steps to Reproduce
Any example with creating `gitlab_project` is fine.

**Comment by cmd-werner-diers** [comment] 2021-11-16 23:47
I believe this is due to the default configuration applied in gitlab at the group level. I hit this issue and the workaround was to set the group level default branch protection as unprotected in order to manage this setting at the project level.

See 
- https://github.com/gitlabhq/terraform-provider-gitlab/issues/667
- https://github.com/gitlabhq/terraform-provider-gitlab/issues/671

**Comment by LDVSOFT** [comment] 2021-11-17 16:26
Workaround using `null_resource` and `local-exec` provisioner:
```
resource "null_resource" "student_remove_protection" {
  for_each = gitlab_project.student

  triggers = {
    repo_id = each.value.id
  }

  provisioner "local-exec" {
    interpreter = ["bash", "-c"]
    command     = "curl -sS --request DELETE --header \"Private-Token: $GITLAB_TOKEN\" \"https://gitlab.com/api/v4/projects/${each.value.id}/protected_branches/${each.value.default_branch}\""
  }
}
```

**Comment by LDVSOFT** [comment] 2021-11-17 16:27
@cmd-werner-diers Yes, thank you, I guess that's group policy that specifies default protection. However, managing default protection on per-project basis would be great too.

**Comment by flybd5** [comment] 2022-01-19 21:12
I just ran into this as well. Shouldn't TF check to see if the master/default repo exists and if so, if it is already protected, instead of failing? Isn't that what idempotency is about?

**Comment by Stromweld** [comment] 2022-01-20 00:20
Are you initializing a repo with readme file option enabled. Without that a default branch is not created nor one protected. Initialize with readme essentially has gitlab create the first branch and commit the readme to it. Since it’s the first it is then protected by default due to group security settings.

**Comment by flybd5** [comment] 2022-01-20 00:29
Yes, with readme file option enabled. Even so the gitlab_branch_protection should see that it is already there and created. Why does it need to fail if it is already there? I looked at the Go code for this and it doesn't look like it has that logic.

**Comment by armsnyder** [comment] 2022-01-22 21:41
> Why does it need to fail if it is already there

>  Isn't that what idempotency is about?

Just to explain the current logic a bit; this is one of the core Terraform design principles, that resources must not automatically import upstream resources. It can result in situations where you apply and then destroy some Terraform config, and you have caused something to be deleted which was present before the apply.

I agree that there is a valid use case of wanting to create a project with an initialized README and also have the default branch protection be manageable in Terraform, without the need to perform multiple applies or imports.

We're open to ideas. Maybe this is a situation where we add an optional attribute to the branch protection resource like `auto_import = true`.

**Comment by flybd5** [comment] 2022-01-22 21:56
This is not a case of expecting the import of an upstream resource. TF had just created the repo. Part of the same script was then designed to set or verify protection. The state is already there as it was created by Gitlab, so TF should not fail if it finds the state of a resource it just created is already as desired. This is Idempotency 101. An additional attribute to do "auto import" is not called for, IMO.

**Comment by armsnyder** [comment] 2022-01-22 22:07
Strictly speaking it is still a case of importing an upstream resource, because the project and the branch protection are different resources, and the Terraform SDK forces us to process each resource independently.

In other words while processing the new `gitlab_project_branch_protection` resource, we don't have a way to check the Terraform configuration for a `gitlab_project`, so we don't know if there is a relationship between the branch protection and the project that was just created. It's entirely possible that the branch protection is for some unrelated project.

Nor do we have the ability to tell Terraform to assume management of a `gitlab_project_branch_protection` resource while it is creating the `gitlab_project` resource. Again the resources are independent.

Terraform is only idempotent for resources that are already in the Terraform state. If you have any suggestions for how to solve this technically, that would be very appreciated. Right now I only see 2 options.
1. Change `gitlab_project_branch_protection` to always auto-import (which is far too dangerous)
2. Add an optional attribute `auto_import` to `gitlab_project_branch_protection` to conditionally enable this behavior (still dangerous, but at least it is opt-in.)

**Comment by flybd5** [comment] 2022-01-22 22:33
> In other words while processing the new gitlab_project_branch_protection resource, we don't have a way to check the Terraform configuration for a gitlab_project...

Sure you do. The Gitlab API lets you [extract a list of protected branches for a project](https://docs.gitlab.com/ee/api/protected_branches.html).

**Comment by armsnyder** [comment] 2022-01-22 22:41
My point is the Terraform SDK does not give us direct access to the configuration. The plugin can only see attributes for one resource at a time.

**Comment by flybd5** [comment] 2022-01-22 22:47
Then TF has a major bug that causes your problem. If a plugin does not have
correct access to the config in order to operate with idempotency because
the overlying tool does not grant access to the necessary info, that's a
major bug in the configuration management world. A temporary workaround
might be an option to allow your code to exit with a warning if you cannot
verify/set the protection.

**Comment by armsnyder** [comment] 2022-02-03 03:56
This seems to be a duplicate of another issue #671 which has more votes, so I am going to close this one. We can move discussion there. There is also more general discussion in #792 if folks want to leave feedback there.

**Closed by armsnyder** 2022-02-03 03:56 UTC
Labels: enhancement
