### ISSUE TITLE
Feature Request: Change the default branch protection of a group

### ISSUE THREAD

**Issue by mick1627** [gitlabhq/terraform-provider-gitlab#667] opened 2021-07-20 09:02 UTC
### Terraform Version
1

### Affected Resource(s)
gitlab_group

### Expected Behavior
Be able to set the default branch protection at group level as describe here  https://docs.gitlab.com/ee/user/group/index.html#change-the-default-branch-protection-of-a-group

### Actual Behavior
not possible actually
By default, default branch has branch protection, and then it not possible to use gitlab_branch_protection. Terraform will raise the following error => Error: protected branch "master" on project "1881" already exists
If I can disable default branch protection at group level, I will be able to manage branch protection using gitlab_branch_protection.

**Comment by armsnyder** [comment] 2021-07-20 22:12
API reference: https://docs.gitlab.com/ee/api/groups.html#new-group

The ask is to add a `default_branch_protection` attribute to the `gitlab_group` resource.

**Comment by cmd-werner** [comment] 2021-07-23 00:59
Hi everyone, in addition to this request I'd like to add an issue that is raised with the default configuration.

By default, gitlab will set the branch protection to be fully protected at the group level. If you (like me) manage the branch protection at the project level, then for new projects the execution will fail with an error similar to:

```
│ Error: protected branch "master" on project "12345678" already exists: {ID:987654321 Name:master PushAccessLevels:[0xc0000adb00] MergeAccessLevels:[0xc0000adb30] UnprotectAccessLevels:[] AllowForcePush:false CodeOwnerApprovalRequired:false}
│ 
│   on resource "gitlab_branch_protection" "main" {
│ 
```

The ability to have this group level feature will allow us to avoid manual configuration on groups.


Thanks

**Comment by mgriffin13** [comment] 2021-07-23 13:54
The two issues are definitely related, but I think they should both be solved. Adding the `default branch protection` setting for a `gitlab_group` resource, but they should also allow `gitlab_branch_protection` to manage an already existing branch protection object in Gitlab.

**Comment by switchboardOp** [comment] 2021-09-07 20:15
https://github.com/gitlabhq/terraform-provider-gitlab/pull/706 implements this and the [upstream go library](https://github.com/xanzy/go-gitlab) has released a version (`0.50.4`) that supports it.

**Comment by callum-stakater** [comment] 2021-12-02 12:50
the new `default branch protection` feature for groups in provider version 3.8 is a bit broken, it seems like it needs 2 applies to actually take effect, we manage groups, projects and project scoped branch protection via some modules and even with this new setting `default_branch_protection = 0`  seems you need to plan/apply twice for a new group for it to be in the desired state, if you also tried to create a repo + branch protection then you are stuffed as the repo is still created with the default branch protection which cant be changed by the `gitlab_branch_protection` resource , kinda not making any progress

**Comment by armsnyder** [comment] 2022-02-04 00:06
@callum-stakater Do you have some debug logs you can share in a gist, showing the multiple applies bug?

`TF_LOG=DEBUG terraform apply`

Also let's move any discussion around the `gitlab_branch_protection` resource conflicting with the default branch protection to #792 and use this issue for the `default_branch_protection` attribute.

**Comment by timofurrer** [comment] 2022-03-06 19:17
I think the initial request of this issue was solved by actually implementing the `default_branch_protection` attribute for the `gitlab_group` resource.

Now, as far as the error described from @callum-stakater: I couldn't reproduce this. Also the tests using a group with a non-default branch protection work fine without multiple applies, e.g:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/bbf465675d44e6b17aec3ce947da0309c377574a/internal/provider/resource_gitlab_project_test.go#L418

@callum-stakater any news on the issue? Since this has been stale now for over a month, I'm marking it `stale` ;)

**Comment by timofurrer** [comment] 2022-03-20 18:47
I'm going to close this - In case anyone experiences some issues, please open another issue with a concrete problem description :) 🎉

**Closed by timofurrer** 2022-03-20 18:47 UTC
Labels: waiting-response
