### ISSUE TITLE
gitlab_topic: 400 error title is missing

### ISSUE THREAD

**Issue by jlamande** [gitlabhq/terraform-provider-gitlab#1085] opened 2022-05-16 10:59 UTC
### GitLab Provider version

3.14.0

### GitLab version

15.0.0-pre 720ba4b77fb

### Terraform version

1.1.9

### Relevant Terraform Configuration

```hcl
resource "gitlab_topic" "topic1" {
  name        = "topic_name"
  description = "description"
}
```

### Relevant log output

```shell
Error: Failed to create topic "topic_name": POST https://gitlab.com/api/v4/topics: 400 {error: title is missing}
```

### Description

the attribute `title` is defined as required by the API : https://docs.gitlab.com/ee/api/topics.html#create-a-project-topic

**Comment by jtymes** [comment] 2022-05-16 11:52
Thanks for the report! This looks like it was added [recently](https://gitlab.com/gitlab-org/gitlab/-/commit/3e9b2ef1665f553c9c289758f24869a2423537cb) as a required field.

**Comment by timofurrer** [comment] 2022-05-16 12:43
Thanks for the report!

However, it's a duplicate of #1043, therefore I'm going to close this one :)

**Closed** 2022-05-16 12:43 UTC
Labels: upstream api alignment, compatibility
