### ISSUE TITLE
Support for protected_environments

### ISSUE THREAD

**Issue by whay-wang-teo-credera-co-uk** [gitlabhq/terraform-provider-gitlab#961] opened 2022-03-16 09:41 UTC
Hello,

I was wondering if there is a roadmap to support protected environments? I see we have this in the RESTAPI but none for the terraform provider

**Comment by timofurrer** [comment] 2022-03-16 09:44
It actually is around the corner, see:

* https://github.com/gitlabhq/terraform-provider-gitlab/pull/938

Duplicate of #444 

🎉

**Closed by timofurrer** 2022-03-16 09:44 UTC
Labels: needs-triage
