### ISSUE TITLE
Can't Import gitlab_group from Gitlab Enterprise

### ISSUE THREAD

**Issue by wazoo** [gitlabhq/terraform-provider-gitlab#196] opened 2019-10-21 20:47 UTC
### Terraform Version
Terraform v0.12.12
+ provider.gitlab v2.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_group

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
File: module/terraform/main.tf
```hcl

provider "gitlab" {
  version = "~> 2.3"
  base_url  = var.gitlab_url
  token = var.gitlab_token
}
resource "gitlab_group" "terraform" {
  name        = "terraform"
  path        = "terraform"
  description = "Terraform Projects"
  visibility_level = "internal"
  lfs_enabled = true
}

```
Command:
```bash
$ terraform import --var-file secrets.tfvars module.terraform.gitlab_group.terraform terraform 
```
### Debug Output
None

### Panic Output
None

### Expected Behavior
Resource should be imported into state.

### Actual Behavior
It seems like no matter the configuration for base_url or using the `GITLAB_BASE_URL` env var have no impact on where it attempts to import resources from, import function seems to always use gitlab.com.

```bash
$ terraform import --var-file secrets.tfvars module.terraform.gitlab_group.terraform terraform 
Acquiring state lock. This may take a few moments...
module.terraform.gitlab_group.terraform: Importing from ID "terraform"...
module.terraform.gitlab_group.terraform: Import prepared!
  Prepared gitlab_group for import
module.terraform.gitlab_group.terraform: Refreshing state... [id=terraform]

Error: GET https://gitlab.com/api/v4/user: 401 {message: 401 Unauthorized}

  on ami/main.tf line 6, in provider "gitlab":
   6: provider "gitlab" {
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create existing project in a GitLab Enterprise instance (I think this just needs to use one that isn't gitlab.com, I don't know that license matters)
2. Import existing project into state.
```bash
 $ terraform import --var-file secrets.tfvars module.terraform.gitlab_group.terraform terraform 
```

### Important Factoids
I have used the token for GitLab that I am using here to create other resources that didn't exist so I know it is working, user is an admin and has been added explicitly to the group in question.

### References
May be related to #193

**Comment by mabunixda** [comment] 2020-02-05 07:43
this errors also occures on gitlab provider v2.2.0

**Comment by armsnyder** [comment] 2020-07-17 22:23
What kind of API token are you using? I've had success importing a group in GitLab EE using a regular API token, using v2.10.0, but I've also seen the error you shared when using a pipeline token.

**Comment by armsnyder** [comment] 2020-09-13 01:06
@wazoo @mabunixda I tried the steps given on GitLab EE 13.2.2 and was unable to reproduce the issue. Import worked fine, using the group path as the import ID. I'm using provider version 2.11.0.

```
❯ terraform import gitlab_group.example example
Acquiring state lock. This may take a few moments...
gitlab_group.kepler: Importing from ID "example"...
gitlab_group.kepler: Import prepared!
  Prepared gitlab_group for import
gitlab_group.kepler: Refreshing state... [id=example]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

Releasing state lock. This may take a few moments..
```

Can one of you try again using the latest provider?

**Comment by armsnyder** [comment] 2020-11-30 07:37
Closing as cannot reproduce, likely fixed in latest version.

**Closed by armsnyder** 2020-11-30 07:37 UTC
Labels: question
