### ISSUE TITLE
Adding SSHKey support for users

### ISSUE THREAD

**Issue by jjasghar** [gitlabhq/terraform-provider-gitlab#75] opened 2019-01-02 23:52 UTC
I'm pretty sure if we just exposed the `SSHKey` in the terraform way, we could have another variable for SSH Keys for the users?

https://github.com/xanzy/go-gitlab/blob/master/users.go#L258

**Comment by armsnyder** [comment] 2020-09-12 21:56
Closing as a duplicate of #40

**Closed by armsnyder** 2020-09-12 21:56 UTC
