### ISSUE TITLE
Add Project Webhooks data source

### ISSUE THREAD

**Issue by pinarruiz** [gitlabhq/terraform-provider-gitlab#1103] opened 2022-05-27 10:18 UTC
### Feature Description

Add support for data sources and resources in order to set up webhooks using terraform.

I have researched the GitLab API and this should be possible ([API / Project / Hooks](https://docs.gitlab.com/ee/api/projects.html#hooks)).

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by pinarruiz** [comment] 2022-05-27 10:22
Might be a duplicate of #680 but i dont know if the scope of that issue takes this one into it.

**Comment by timofurrer** [comment] 2022-05-28 17:04
Thanks for the request @pinarruiz 🎉 

Not sure if you've noticed but a resource for the Project Hooks API already exists with [`gitlab_project_hook`](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/project_hook). There isn't a data source though.

What's missing is the equivalent for the Group Hooks API which you correctly pointed out would be a duplicate of #680.

Is there something you miss in the already existing `gitlab_project_hook` resource? Otherwise, I'll just leave this issue open to implement the missing data source for it. WDYT?

**Comment by pinarruiz** [comment] 2022-05-28 17:35
Whoops, I might be blind on that one, thanks for pointing the url 😄.

In that case, I do not see anything that needs to be added to the webhook resource, and leaving the issue open for the data source would be a great idea!

Thanks

**Closed** 2022-08-08 18:42 UTC
Labels: enhancement, good first issue, data-source
