### ISSUE TITLE
gitlab_group_share_group Provider produced inconsistent result after apply error

### ISSUE THREAD

**Issue by Lena-nfb** [gitlabhq/terraform-provider-gitlab#646] opened 2021-07-09 13:17 UTC
Hi there,

I am trying to share a group to another group but the provider throws an error and I would really appreciate your help.
Both groups already exist in Gitlab. 

### Terraform Version

0.15.3
Also tried with 0.13.4 

### Affected Resource(s)

gitlab_group_share_group 

### Terraform Configuration Files
```hcl
resource "gitlab_group_share_group" "test" {
  group_id       = "12345" //dummy group_id
  share_group_id = "6789"  // dummy group_id
  group_access   = "maintainer"
}
```

### Debug Output
```
gitlab_group_share_group.test: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to gitlab_group_share_group.test, provider "provider[\"registry.terraform.io/gitlabhq/gitlab\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behavior
Groups are associated and terraform state to be updated accordingly.

### Actual Behavior
Groups are associated but terraform state is not updated. If you run `terraform apply` again it throws an error that association already exists. 

### Important Factoids
versions 3.5.0 and 3.6.0 of the provider were used and same error occurred.

**Comment by bryceml** [comment] 2021-07-28 19:44
I got this, it appeared to be an issue with gitlab's api itself.  I checked via curl and it saw the same things.

I think it's something wrong in their database.

We just deleted the groups we were sharing with (share_group_id) and re-created them, and then tried to share again and everything works.

**Comment by timofurrer** [comment] 2022-01-28 23:15
@Lena-nfb are you still experiencing this issue?

**Comment by timofurrer** [comment] 2022-03-26 17:24
Since there hasn't been any activity from @Lena-nfb I'm taking the liberty to close this. I wasn't able to reproduce this issue either and with @bryceml comment I guess the issue was fixed upstream.

@Lena-nfb in case you still have issues on a recent GitLab instance using an up to date provider, please let us know and we'll look at it again! 🎉

**Closed by timofurrer** 2022-03-26 17:24 UTC
